In [2]:
import cv2
import datetime
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd 

In [3]:
poses = pd.read_csv("../Dataset/poses/00.txt", delimiter=' ', header=None)
poses.head()

0             1             2             3             4         5   \
0  1.000000  9.043680e-12  2.326809e-11  5.551115e-17  9.043683e-12  1.000000   
1  0.999998  5.272628e-04 -2.066935e-03 -4.690294e-02 -5.296506e-04  0.999999   
2  0.999991  1.048972e-03 -4.131348e-03 -9.374345e-02 -1.058514e-03  0.999997   
3  0.999980  1.566466e-03 -6.198571e-03 -1.406429e-01 -1.587952e-03  0.999993   
4  0.999964  2.078471e-03 -8.263498e-03 -1.874858e-01 -2.116664e-03  0.999987   

             6             7             8             9         10  \
0  2.392370e-10  3.330669e-16  2.326810e-11  2.392370e-10  1.000000   
1 -1.154865e-03 -2.839928e-02  2.066324e-03  1.155958e-03  0.999997   
2 -2.308104e-03 -5.676064e-02  4.128913e-03  2.312456e-03  0.999989   
3 -3.462706e-03 -8.515762e-02  6.193102e-03  3.472479e-03  0.999975   
4 -4.615826e-03 -1.135202e-01  8.253797e-03  4.633149e-03  0.999955   

             11  
0 -4.440892e-16  
1  8.586941e-01  
2  1.716275e+00  
3  2.574964e+00  
4  3.432648e+00

In [4]:
print(f'Number of Rows = {poses.shape[0]}')
print(f'Number of Columns = {poses.shape[1]}')

Number of Rows = 4541
Number of Columns = 12


In [6]:
print('Initial Pose')
print(poses.iloc[0])

Initial Pose
0     1.000000e+00
1     9.043680e-12
2     2.326809e-11
3     5.551115e-17
4     9.043683e-12
5     1.000000e+00
6     2.392370e-10
7     3.330669e-16
8     2.326810e-11
9     2.392370e-10
10    9.999999e-01
11   -4.440892e-16
Name: 0, dtype: float64


In [8]:
initial_pose = np.array(poses.iloc[0]).reshape(3,4).round(3)
print("Rotation and Translation Matrix for the initial pose")
print(initial_pose)

Rotation and Translation Matrix for the initial pose
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -0.]]
